### ISSUE TITLE
Mappa girabile

### ISSUE THREAD

**Issue by freerafiki** [Lychfindel/v4w_website#104]
https://www.npmjs.com/package/leaflet-rotate-map

**Comment by Lychfindel** [comment]
Da quanto capisco questo non sembra un plugin ma una branch del codice di leaflet (https://github.com/ronikar/Leaflet/tree/rotate-package), quindi installarlo probabilmente non è così semplice e, soprattutto, non è così sicuro che sia stabile.

Una cosa interessante però è che né osm né googlemaps implementano la rotazione su browser mobile, la rotazione funziona solo su app

**Comment by freerafiki** [comment]
rimuovo, risolta nel nuovo frontend
