### ISSUE TITLE
calcolo dei tempi di percorrenza

### ISSUE THREAD

**Issue by lucatastrophe** [Lychfindel/v4w_website#13]
implica il cambio di metodo per il calcolo del percorso breve (senza ponti), in modo che ritorni anche la lunghezza del percorso. 
Per il prercorso con ponti rischia di essere più complicato: un'idea potrebbe essere far pesare i ponti 100000, in modo che dividendo la lunghezza per 100000 e sottraendolo alla lunghezza, ci ritroviamo con la lunghezza giusta. Il difetto è che ci toglie la possibilità di avere una "scala di pigrizia", anche se non ci sono particolarmente affezionato. La soluzione lunga è fare una piccola funzione che calcola la lunghezza del percorso senza usare i metodi di networkx (o magari c'è un metodo di nt che calcola solo la lunghezza!)

**Comment by Lychfindel** [comment]
Forse sarebbe da aprire un'altra issue, ma dobbiamo pensare se vogliamo mantenere la "scala di pigrizia" e in caso come implementarla o come cambiarla

**Comment by freerafiki** [comment]
ma se ritorniamo il numero di ponti, poi possiamo sottrarre il numero di ponti piu il valore della "scala di pigrizia" e abbiamo la distanza normale. 
`distSenzaPonti = distTotale - numPonti * distCheValeUnPonte`
E io direi che **indipendentemente da questa risposta, ritorniamo il numero di ponti nella versione pigra**.
Poi avremmo che la persona deve fare N metri, e ha P ponti. Possiamo ritornare la velocita che ci mette a fare N metri (che sarebbe come se non avessimo usato la funzione di peso dei ponti), o usare un fattore aggiuntivo
`tempo = dist / velocita + f(P)`
e f(P) e una funzione che ci da la differenza tra una strada con 0 ponti e una strada con P ponti. Ma forse non serve tutto cio, perche non la usiamo nel caso normale, quindi ritorniamo solo la velocita con la formula classica e siamo a posto.

**Comment by lucatastrophe** [comment]
Secondo me andrebbe scritta una funzione che "rilegga" il percorso che viene dato da networkx e ne possa estrarre gli attributi degli archi per calcolare il tempo di percorrenza, il numero di ponti ed eventualmente altre informazioni. Questo perché in fin dei conti possiamo usare barba trucchi per ricalcolarci il numero di ponti attraversati, ma se diamo un peso ai ponti, in ogni caso non estraiamo la strada più corta. La ricerca base invece deve proprio trovare la strada più corta, e con questa funzione ci potrebbe dare anche le info sui ponti.

**Comment by freerafiki** [comment]
edges_info diventera un array di geojson - ogni edge e un geojson
ogni edge avra prpoperty che determinera come viene disegnato
link qua --> https://leafletjs.com/examples/geojson/

**Comment by Lychfindel** [comment]
Bisogna ricordarsi che i Rii Blu hanno velocità 0 come spiegato in #51

**Comment by freerafiki** [comment]
per le strade a piedi sembra funzionare (molto basico, ma i tempi ci sono), ma per le strade in barca non ancora

**Comment by Lychfindel** [comment]
Ora funziona anche per le strade in barca. Rimane estremamente base e limitato, però per ora chiuderei la issue e in caso la riapriamo
