### ISSUE TITLE
Sostituzione automatica delle abbreviazioni "s." per "san" e simili

### ISSUE THREAD

**Issue by Lychfindel** [Lychfindel/v4w_website#15]
Relativo a #3 e a #5 ma lo apro come bug.
Cercando "campo s.polo" trova "campo san gerardo", cercando "campo san polo" trova invece il luogo giusto.
Cercando "s. polo 1424" trova giustamente il civico "san polo 1424"

**Comment by freerafiki** [comment]
@Lychfindel ma in teoria adesso e risolta no? O dici che s. --> san era solo uno e lo teniamo aperto per altre possibilita (tipo campo DE --> campo DI o robe in veneziano?)

**Comment by Lychfindel** [comment]
Ah se l'abbiamo già corretto chiudiamo!
