### ISSUE TITLE
Riorganizzazione Database

### ISSUE THREAD

**Issue by freerafiki** [Lychfindel/v4w_website#16]
Proporrei di avere gli indirizzi salvati cosi

| Sestieri  | Area      |  Toponimo | StopWords | ParolaChiave | NumeriCivici | Coordinate | 
| -------- | -------- | -------- | -------- | -------- | -------- | -------- |
| Cannaregio  | / |  Campo San Giovanni e Paolo | Campo, San | Giovanni e Paolo  | 3100-3200 | coords | 
| Cannaregio  | / | Barbaria delle Tole | Barbaria | Tole  | 3200-3400 | coords | 
| Santa Croce  | Santa Marta | Ponte Santa Marta | Ponte, Santa | Santa Marta  | 167-169 | coords | 

In modo da avere piu liberta nella ricerca e renderla piu flessibile.
Userei un dizionario, perche numericivici e coordinate sarebbero liste (quindi cerchiamo sempre una strada, ponte, piazza, calle e solo dopo il numero)

Poi magari sarebbe da avere una lista diversa solo per i sestieri
| Sesitere | Civici (lista) | Coordinate (lista) |
| -------- | -------- | -------- |
| Cannaregio   | 1-6572   | coordinate   |
| San Polo   | 1-8000   | coordinate  |

in modo che se un utente cerca il sestiere, cerchiamo solo il numero

**Comment by lucatastrophe** [comment]
mi sono appena reso conto di una cosa: dobbiamo porci la domanda di come verranno strutturati i punti di interesse. Infatti, se attribuiamo ad un punto di interesse una coordinata, allora possiamo mantenere la struttura che hai proposto, ma se invece attribuiamo al punto di interesse un indirizzo, allora sarebbe più comodo che ogni indirizzo avesse una sua "riga" in modo da potergli dare degli attributi, come per esempio il nome del negozio. 
A questo proposito ho scaricato i dati usati da venice project center per costruire la mappa dei negozi e vi scrivo qui l'header:

|id | shop name | shop address | economic code | economic activity | Year shop opened | Year shop closed | physical person? | Dem of person | Gender of Person | Age of Person
|------|-------|------|-----|----|-----|----|------|------|------|----|

con un piccolo script potremmo trovare le corrispondenze tra "shop address" (non sono super regolari come formattazione, ma con sequence matcher ce la caviamo bene) e gli indirizzi di civico e aggiungere come attributo al civico "shop name" e "economic activity".

Se invece vogliamo procedere con la strategia POI= punto e non indirizzo, questo può essere interessante per estrarre info da OSM: https://github.com/MorbZ/OsmPoisPbf

**Comment by freerafiki** [comment]
si hai ragione. Allora bisogna trovare un metodo furbo. Ho un'idea per cambiare leggermente la struttura, ma e un po work in progress. Provo a esporre. 
Forse cambiando cosi tanto torna a qualcosa che avevate detto voi, o forse non ha nessun senso. Io provo, casomai lasciamo la struttura attuale e pazienza

**TL;DR**
L'idea e di cercare di trovare come adesso, e poi convertire la cosa trovata in "sestiere, numero". Indipendentemente che sia un bar o la casa dove la gente vive (sopra il bar) in modo da evitare di cercare lo stesso indirizzo o la stessa calle piu volte.

**SPIEGAZIONE VERA**
Dividiamo le cose. Una e per le coordinate: cambiamo le due liste dove c'erano _numeri civici_ e _coordinate_ con _sestiere, numero civico_ e _coordinate_.

Dall'altra parte abbiamo tutti i dati che vogliamo per la ricerca. Per noi, cerchiamo le cose, e una volta trovate, le convertiamo in _sestiere, numero civico_ e da la accediamo alle coordinate.

Graficamente, abbiamo una tabella (database, dizionario o quello che volete)
|id | sestiere | calle/denominazi |  tipo | .. | .. | quello che volete | .. | .. |
|-----|-----|-----|-----|-----|-----|-----|-----|-----|

Ok. Ora abbiamo una funzione ricerca che separa il numero
```
    testo, numero = separa(input_utente)
    riga_trovata = ricerca(testo)
```
da quello che l'utente cerca noi troviamo una riga. Questa riga puo contenere un sacco, perche li trucco e che la ricerca non cerca in tutta la tabella, ma solo in 2 colonne
```
def ricerca(input):
       sestieri = np.unique(tabella_grande['sestiere'])
       denominazi = tabella_grande['denominazi']
       (se vogliamo, POI = tabella_grande['tipo==POI']
       cerca con la funzione di ale, trova indice ind
       ritorna riga[ind]
```
Quindi a livello computazionale e indifferente la grandezza della tabella, l'unica cosa che cambia e che nella ricerca non abbiamo i numeri, quindi facciamo meno confronti.
Una volta che abbiamo la riga che vogliamo, selezioniamo il sestiere 
`sestiere = riga_trovata['sestiere']`
e accediamo alla seconda tabella, (matrice, tabella, dizionario, uguale) e otteniamo la coordinata
la tabella sarebbe

|sestiere|numero civico|coordinata|
|-----|-----|-----|

e abbiamo quindi
`coordinata = tabella_piccola(sestiere, numero)`
dove numero e quello ottenuto dalla funzione `separa(input_utente)' sopra

**Comment by Lychfindel** [comment]
Io sono totalmente d'accordo con Palma.
Io proporrei di fare un database solo per l'idea futura che un utente poi possa inserire informazioni, e secondo me il database si presta meglio a questo. A livello di ricerca su python non cambierebbe niente perché immagino ci siano funzioni per caricare le tabelle di un database in un array di numpy (come facciamo ora con i file txt) o in una tabella di pandas, quindi come ora potremmo caricare tutto all'inizio nel formato che preferiamo e poi fare la ricerca

**Comment by freerafiki** [comment]
io ho visto che c'erano un sacco di open source tools per GraphQL. Ignoro cosa sia, ma sembrava legato al database. 
Da Wikipedia quoto: "_GraphQL is an open-source data query and manipulation language for APIs, and a runtime for fulfilling queries with existing data. [..] It allows clients to define the structure of the data required, and the same structure of the data is returned from the server, therefore preventing excessively large amounts of data from being returned, but this has implications for how effective web caching of query results can be. The flexibility and richness of the query language also adds complexity that may not be worthwhile for simple APIs.[7][8][9] It consists of a type system, query language and execution semantics, static validation, and type introspection. [..] GraphQL servers are available for multiple languages, including Haskell[11], JavaScript,[12] Perl,[13] Python,[14]_"
Il link di python e questo: [Graphene Python](https://graphene-python.org/) e dicono: _"We believe that GraphQL is the next big thing after peanut butter and REST_"

Praticamente sembra una specie di Database ma senza essere un database. GraphQL e stato inventato da Facebook, ma e ora mantenuto dalla Linux Foundation, ed e open source.

Altri link su GraphQL: 
- [GraphQL Code Generator](https://graphql-code-generator.com/)
- [Get realtime GraphQL APIs instantly](https://hasura.io/)

Ancora non capisco cosa sia, ma prima di dimenticarmelo, lo scrivo qua, magari qualcuno di voi conosce o ha sentito e puo esserci utile. Se e una cavolata, pazienza, cancelliamo il commento dopo

**Comment by lucatastrophe** [comment]
- Modificare la struttura con: sestieri intesi come insiemi di ricoprimento disgiunti. zone a denominazione locale con collegamenti uno a molti verso street e collegamenti molti a molti verso i sestieri. Aggiungere alle street il json del poligono. Permettere location senza indirizzo.

**Comment by lucatastrophe** [comment]
Correggere errori database

**Comment by Lychfindel** [comment]
Abbiamo deciso la struttura del database, quindi chiudo la issue
