### ISSUE TITLE
controllare il file populate_db.py 

### ISSUE THREAD

**Issue by freerafiki** [Lychfindel/v4w_website#18]
1. aggiungere lista di POI che abbiamo gia
2. aggiungere moli come POI

**Comment by freerafiki** [comment]
controllare e magari creare un workflow che ci permetta sempre di dargli un shp e che lui gestisca tutto e aggiorni il database senza robe vuote

**Comment by lucatastrophe** [comment]
Mancano i moli, ma il resto è una meraviglia, tolgo "high priority"

**Comment by freerafiki** [comment]
mancherebbe anche aggiornare la funzione `check_db` o comunque avere una funzione di test valida secondo me prima di chiuderla, sono d'accordo comunque con la rimozione dell'high priority

**Comment by freerafiki** [comment]
fatto
