### ISSUE TITLE
decisione database - sqlite o mysql?

### ISSUE THREAD

**Issue by freerafiki** [Lychfindel/v4w_website#19]
capire, decidere, attivare

**Comment by Lychfindel** [comment]
Probabilmente quello migliore per le cose geografiche è PostGIS, però ho trovato questa libreria che estende SQLAlchemy che è molto molto interessante! https://geoalchemy-2.readthedocs.io/en/latest/spatialite_tutorial.html
Potrebbe facilitare molto la vita nel fare le ricerche di cose geografiche all'interno del database, quindi secondo me potrebbe essere una buona via di mezzo visto che il passaggio a PostGIS (o altro database più adatto) lo vedo molto lontano!

**Comment by freerafiki** [comment]
postgresql vince :)
