### ISSUE TITLE
Grafica migliore

### ISSUE THREAD

**Issue by freerafiki** [Lychfindel/v4w_website#21]
invadiamo il sito bootleaf con una ricercamigliore
https://github.com/bmcbride/bootleaf

**Comment by Lychfindel** [comment]
Si può anche pensare di evitare bootstrap e lavorare solo con [plugin leaflet](https://leafletjs.com/plugins.html). Un po' di esempi:
-  Dialoghi modali: 
  1. https://github.com/mapshakers/leaflet-control-window
  2. https://github.com/w8r/Leaflet.Modal
- Sidebar: 
 1. https://github.com/turbo87/sidebar-v2/ 
 2. https://github.com/noerw/leaflet-sidebar-v2
- Toolbar:
 1. https://github.com/Leaflet/Leaflet.toolbar

**Comment by Lychfindel** [comment]
Direi che la grafica è migliorata e questa issue si può chiudere!
