### ISSUE TITLE
Modificare funzione di ricerca

### ISSUE THREAD

**Issue by freerafiki** [Lychfindel/v4w_website#23]
1. `find_address_in_db` cerca e ritorna una string che `fetch_coordinates` usa. Se `find_address_in_db` ritorrnasse l'oggetto, `fetch_coordinates` dovrebbe solo estrarre le coordinate e forse non servirebbe neanche usare `fetch_coordinates`

2. Gestire meglio alcuni casi, come per esempio:
- civico sbagliato e sestiere (o strada giusta) - da errore, dovrebbe tornare i 5 civici piu vicini
- poi senza numero civico - cerca una shape, dovrebbe cercare le coordinate (latitude e longitude)

3. (OPZIONALE) la ricerca potrebbe ritornare solo alcune colonne del database per migliorare le performances

**Comment by Lychfindel** [comment]
Questa issue potrebbe risolvere #3

**Comment by freerafiki** [comment]
la ricerca ora funziona. Non sara la piu veloce o la migliore, ma i problemi descritti qua sono risolti
