### ISSUE TITLE
usare in maniera furba i metodi delle classi all'interno di models.py

### ISSUE THREAD

**Issue by freerafiki** [Lychfindel/v4w_website#24]
1. `repr` dovrebbe ritoranre l'oggetto

2. `str` dovrebbe ritornare il nome (per strade e sestiere il nome, per POI nome o un codice predefinito se il POI non ha nome)

3. `get_fancy_description` o chiamiamolo come vogliamo ci da una descrizione completa. Questo viene usato per visualizzare sulla pagina web la cosa trovata o le cose che abbiamo trovato quando non siamo sicuri, quindi piu informazioni possibili

**Comment by Lychfindel** [comment]
Questa issue potrebbe risolvere anche #3
