### ISSUE TITLE
ricerca asincrona

### ISSUE THREAD

**Issue by freerafiki** [Lychfindel/v4w_website#26]
studiare la ricerca asincrona

1. come funziona mentre l'utente digita sulla barra di ricerca

2. possiamo gestire il tutto asincrono? pythonanywhere + threads?
2b. asincrona e solo esatta o anche con wuzzy?

**Comment by Lychfindel** [comment]
https://www.pythonanywhere.com/forums/topic/1563/
Su pythonanywhere non è abilitato il multithreading, l'unica soluzione quindi è andare tramite Ajax (che forse era la soluzione pensata fin dall'inizio, ma tant'è…)

**Comment by freerafiki** [comment]
ajax ce l'abbiamo!
