### ISSUE TITLE
Multipoligoni

### ISSUE THREAD

**Issue by freerafiki** [Lychfindel/v4w_website#27]
fastidiosi - dobbiamo gestirli e convertirli a poligoni (multipoligoni non sono neanche supportati da leaflet

**Comment by freerafiki** [comment]
non sono sicuro si possa convertire i multipoligoni a poligoni, c'e una differenza teorica ([discussione qui](https://gis.stackexchange.com/questions/225368/understanding-difference-between-polygon-and-multipolygon-for-shapefiles-in-qgis)) e a occhio e croce quelli che abbiamo sembrano più multipoligoni, perchè non sempre sono pieni! Quindi o si correggono i poligoni dei ponti, o disegniamo semplicemente poligono per poligono.
Invece di creare una shape con tutti i punti, passiamo una lista di poligoni (nel caso del poligono ce n'è uno solo, nel caso del multipoligono più di uno, e disegniamo su js quelli che arrivano)

**Comment by Lychfindel** [comment]
Risolto organizzando le shape in dizionari geoJSON e disegnando direttamente il geoJSON tramite leaflet
