### ISSUE TITLE
Automatizzare download POI

### ISSUE THREAD

**Issue by Lychfindel** [Lychfindel/v4w_website#29]
Bisognerebbe eliminare lo scaricamento dei poi tramite Java e automatizzarlo (in modo da farlo andare ad esempio una volta a settimana).
La cosa bella è che (come quasi sempre) è già tutto fatto: https://towardsdatascience.com/loading-data-from-openstreetmap-with-python-and-the-overpass-api-513882a27fd0

Qua la libreria utilizzata: http://overpass-api.de/
Qua un sito che fa la stessa cosa della libreria ma da browser: http://overpass-turbo.eu/ (basta che vi spostiate su venezia e runniate 
```
node
  [amenity]
  ({{bbox}});
out;
```

**Comment by freerafiki** [comment]
bellissima idea! +1

**Comment by freerafiki** [comment]
ce l'abbiamo fatta! Codice nella cartella poi!
