### ISSUE TITLE
Rappresentazione mappa

### ISSUE THREAD

**Issue by Lychfindel** [Lychfindel/v4w_website#31]
Attualmente noi stiamo utilizzando la mappa base di OSM.
Ci sono alcune cose che non mi piacciono, in particolare il fatto che alcuni simboli di POI siano mostrati e la maggior parte di questi sono alberghi e b&b.
Propongo di avere una rappresentazione nostra in cui decidiamo noi cosa mostrare e cosa no (ad esempio io proporrei solo nomi strade e fontanelle).
Cercando un po' in internet mi pare di capire che si possano creare i tiles personalizzati usando questo: http://maperitive.net/ oppure possiamo trovare online qualcuno che abbia già dei tiles che ci vadano bene.
Se creiamo i nostri tiles con maperitive possiamo anche utilizzarli direttamente senza doverli ogni volta caricare da OSM (non so però quanto pesino i file)

**Comment by freerafiki** [comment]
bello! secondo me questo avrebbe anche un vantaggio non trascurabile se vogliamo passare ad una versione offline. Avere i nostri tiles (o comunque averli scaricati e poterli mettere in una cartella) ci permetterebbe di avere l'app _self-contained_, cioe senza bisogno di collegamenti esterni (scaricando le varie cose di bootstrap anche). Quindi si potrebbe avere l'app quasi come docker (una specie di piccola macchina virtuale) e avere diverse installazioni (sul nostro server, in locale, o dove vogliamo) e secondo me a livello di performance sarebbe bomba, perche dovrebbe diminuire il tempo delle richieste, penso. Ed essere disponibile come servizio offline se ti scarichi la app, con zero modifiche da parte nostra tra la app _online_ e quella _offline_.

**Comment by freerafiki** [comment]
http://geoserver.org/ open source geoserver che potremmo usare per avere le mappe senza dover fare richieste a OSM tutto il tempo. Sembra che debba essere installato da qualche parte, quindi una volta che avremo un server.

**Comment by freerafiki** [comment]
maputnik e maptileserver e ci siamo
