### ISSUE TITLE
Eliminare file pesanti da repo

### ISSUE THREAD

**Issue by Lychfindel** [Lychfindel/v4w_website#33]
Gli shapefile sono molto pesanti e sono utili solo in fase di inizializzazione del database o di creazione del grafo. Il fatto che siano pesanti, oltre a un mio problema personale visto che ho il computer strapieno, è la causa per cui su pythonanywhere abbiamo poco spazio libero. Propongo quindi di eliminare i file dalla repo e, in caso di necessità, scaricarli da una cartella online.
Qua c'è una vecchia cartella condivisa che avevo creato tempo fa, potremmo usare questa o crearne un'altra da un'altra parte: https://mega.nz/folder/ModGiYpT#ga7VXQeAAbGKDejkSX2gpg

**Comment by freerafiki** [comment]
io propongo di caricarli sul nostro nextcloud, in teoria se creiamo un link sharable sono accessibili dall'esterno (ma non modificabili senza account) e potremmo in caso di necessita richiamarle da la - ma temporaneamente anche la cartella mega va bene

**Comment by Lychfindel** [comment]
Ottimo se su nextcloud si può fare link sharable dall'esterno!

**Comment by freerafiki** [comment]
Facciamo subito un test: io riesco a vederlo da un altro browser qui
[OpenDataVenezia](https://next.eclabs.de/s/x3TgbF2JmRw5XE8)
Ora la Issue diventa eliminare i file di cui non abbiamo bisogno :) anche perche rubano il tuo spazio su nextcloud, ma non il nostro, perche l'ho creata dentro il progetto! se poi finisci lo spazio, la creo fuori.

Magari su github lasciamo un solo .md file con il link alla cartella, nel caso uno cerchi i file

**Comment by Lychfindel** [comment]
Forse la risposta è qua: https://help.nextcloud.com/t/upload-and-download-files-from-nextcloud-by-python-script/54647

**Comment by freerafiki** [comment]
molto bello! L'esempio sul [github e esattamente quello che ci serve!](https://github.com/owncloud/pyocclient). Crea una cartella, carica dei file, e crea il link per esterni.

pensavo che in realta bastasse caricare i file a mano, ma in effetti con python e piu figo. Manca da implementare la parte in cui li scarichiamo dal portale opendata di venezia pero, quindi lo lascerei _da fare_, ma non particolarmente urgente.
Almeno per ora, abbiamo spostato i file a mano e siamo a posto, almeno temporalmente, no?

Ora la cartella linkata sopra e pubblica da vedere, quindi i file si possono scaricare normalmente come file (per farlo con python [qui un esempio](https://likegeeks.com/downloading-files-using-python/) ) e se ci servono li scarichiamo, e se dobbiamo cambiarli li cambiamo a mano.

Quindi, direi:
- 1. per ora lasciamo i file su nextcloud e in caso di necessita li scarichiamo da pythonanywhere
- 2. aggiungiamo il codice per caricarli su nextcloud via python
- 3. aggiungiamo il codice per scaricarli dal portale di opendata via python.
- 4. settiamo una task che una volta al mese fa le seguenti cose: a) scarica i dati da opendata, b) li carica su nextcloud, c) li scarica su pythonanywhere e aggiorna il db, d) controlla il db, e) scrive un report. 

Cosi facendo sappiamo che su nextcloud ci sono sempre i file piu recenti e sono sincronizzati con il nostro sito.
