### ISSUE TITLE
Convertitore

### ISSUE THREAD

**Issue by freerafiki** [Lychfindel/v4w_website#37]
piccoli metodi in _utils.py_ o in un'altra libreria per convertire
- un numero in metri a un numero nel nostro sistema di riferimento (o viceversa)
- una coordinata + un numero in metri in una coordinata nel nostro sistema di riferimento

**Comment by freerafiki** [comment]
Sembra che ci sia una soluzione super semplice [1] (la seconda risposta), usando un'approssimazione:

```
Length in meters of 1° of latitude = always 111.32 km
Length in meters of 1° of longitude = 40075 km * cos( latitude ) / 360
```

che assume la circonferenza della terra sia 40075 km.
In realtà la questione è un po' più complessa, è spiegata nella prima risposta [1] e in [2] in maniera più completa.
C'è una formula di Haversine [3] che spiega come passare da latitude/longitude a metri, ma non l'opposto.
C'è una pagina di wikipedia sulle coordinate, ma mi pare confusa [4].

Io direi che possiamo implementare una versione _semplice_ in cui usiamo il trucco, e poi magari chi ha voglia implementa la versione più complicata (o lo lasciamo nei TODO per possibili contributori come esempio)

Resources:
[1] https://stackoverflow.com/questions/639695/how-to-convert-latitude-or-longitude-to-meters 
[2] http://www.movable-type.co.uk/scripts/latlong.html
[3] https://en.wikipedia.org/wiki/Haversine_formula
[4] https://en.wikipedia.org/wiki/Geographic_coordinate_system

**Comment by Lychfindel** [comment]
L'approssimazione a me sembra ottima, soprattutto perché a noi serve soprattutto per determinare un raggio di interesse (tipo cercare i poi che stanno entro una certa distanza da un dato punto). Per la distanza tra due punti utilizziamo già la formula di Haversine (o di Vincenty non ricordo), quindi quella dovrebbe essere giusta.
Propongo quindi di fare due metodi: `degree2meter` e `meter2degree` e poi magari lasciare cose più complicate e precise come TODO

**Comment by freerafiki** [comment]
d'accordo! magari li chiamerei `degree2meter_approx` e `meter2_degree_approx` i nostri e lascerei  `degree2meter` e `meter2_degree` come cose da fare. A me sembra molto bella l'idea di creare dei metodi vuoti con la spiegazione per aiutare chi ha voglia di contribuire. Secondo me potrebbe funzionare.
