### ISSUE TITLE
iFrame handling

### ISSUE THREAD

**Issue by freerafiki** [Lychfindel/v4w_website#42]
Come possiamo gestire gli iFrame in modo che possiamo embeddare la nostra pagina, ma non tutti possono?

**Comment by freerafiki** [comment]
Solution: 
Set a response header with X-Frame Options

Ci sono 3 opzioni:
- DENY (nessuno può iframare)
- SAMEORIGIN (solo noi da pagine di dequa)
- ALLOW-FROM (lista di chi può iframarci)

Resources:
- [how to set response header in flask](https://stackoverflow.com/questions/25860304/how-do-i-set-response-headers-in-flask
)
- [How to set response headers for all sites](https://stackoverflow.com/questions/30717152/python-flask-how-to-set-response-header-for-all-responses)
- [ma cos'è un response header, ci chiediamo](https://flask.palletsprojects.com/en/1.1.x/api/#flask.Response)
- [open source library for doing it](https://github.com/twaldear/flask-csp)

bisogna che capisca un po' meglio dove e come va inserito, sembrerebbe che nel routing una volta che siamo sulla creazione della pagina (calcolo strade ecc) possiamo fare`resp = Flask.response()` e là inserirgli `resp.headers['Access-Control-Allow-Origin'] = 'ALLOW-FROM tatata'`, però non so se va fatto una volta per tutti, su ogni pagina, e soprattutto cosa fare con l'oggetto `resp` una volta settato l'header. 
Un giorno con più calma me lo leggo, intanto scrivo qua così non mi dimentico

**Comment by Lychfindel** [comment]
Ricommento quesa vecchia issue.
Qua la documentazione flask per settare x-frame-options: https://flask.palletsprojects.com/en/1.1.x/security/#x-frame-options
La mia proposta è di mettere per www.dequa.it il blocco degli iframe, e poi fare un routing apposito solo per gli iframe (tipo www.dequa.it/embed/etc) in cui fare anche un check di api_key per cui avere il controllo di chi può e chi non può includere la mappa sul sito. Ad esempio google utilizza come src per gli iframe questo formato: https://www.google.com/maps/embed/v1/place?key=API_KEY&q=Space+Needle,Seattle+WA

**Comment by freerafiki** [comment]
rimuovo, risolta nel nuovo frontend
