### ISSUE TITLE
Velocità dei canali nulle

### ISSUE THREAD

**Issue by Lychfindel** [Lychfindel/v4w_website#51]
Alcuni canali hanno VEL_MAX=0, questo comporta un errore nel calcolo del tempo di percorrenza perché dividiamo per 0.

Per replicare l'errore:
`http://127.0.0.1:5000/ndemo?partenza=san+polo+1424&boat=on&arrivo=cannaregio+3793`
Output:
```
DEBUG in interface: the dictionary with all the info: {'time': inf, 'n_ponti': 0, 'shape_list': [{'type': 'Feature', 'properties': {'street_type': 'canale', 'vel_max': 1, 'solo_remi': 0}, 'geometry': {'type': 'LineString', 'coordinates': ((12.3307791849918, 45.43774879961933), (12.33142660910582, 45.43655561221177))}}, {'type': 'Feature', 'properties': {'street_type': 'canale', 'vel_max': 0, 'solo_remi': 1}, 'geometry': {'type': 'LineString', 'coordinates': ((12.3303590658322, 45.4382717632739), (12.3305806975086, 45.4380363303039), (12.3307791849918, 45.4377487996193))}}, {'type': 'Feature', 'properties': {'street_type': 'canale', 'vel_max': 0, 'solo_remi': 1}, 'geometry': {'type': 'LineString', 'coordinates': ((12.3328574523152, 45.4409111234729), (12.3326511277619, 45.4406238865689), (12.3322626882259, 45.440266307902), (12.3321706086839, 45.4401674440296), (12.3319064288472, 45.4398837966251), (12.3319063606728, 45.4398837239225), (12.3318587370494, 45.4398293338764), (12.3318015739624, 45.4397614900219), (12.3317915310734, 45.439749735601), (12.331706575158, 45.4396429493055), (12.331677467606, 45.4396061805684), (12.3313440759823, 45.4392286070447), (12.3309607301588, 45.4388557319174), (12.3309418132785, 45.4388365690287), (12.3307868124344, 45.4386598552606), (12.3303818589894, 45.4382924435766), (12.3303590658322, 45.4382717632739))}}, {'type': 'Feature', 'properties': {'street_type': 'canale', 'vel_max': 5, 'solo_remi': 0}, 'geometry': {'type': 'LineString', 'coordinates': ((12.3342770406376, 45.4424250209537), (12.3341969843537, 45.4423783422195), (12.3337461398324, 45.4418663056186), (12.3337125206286, 45.4418324015711), (12.3334912471267, 45.4415651194163), (12.3334442393309, 45.44151105857), (12.3333002338591, 45.4413547542732), (12.3331205086382, 45.4411827509701), (12.3328574523152, 45.4409111234729))}}, {'type': 'Feature', 'properties': {'street_type': 'canale', 'vel_max': 5, 'solo_remi': 0}, 'geometry': {'type': 'LineString', 'coordinates': ((12.3348300088752, 45.4421358530693), (12.3346298327722, 45.4422413881069), (12.3346029626651, 45.4422555652129), (12.3343297925791, 45.4423975934472), (12.3342770406376, 45.4424250209537))}}, {'type': 'Feature', 'properties': {'street_type': 'canale', 'vel_max': 1, 'solo_remi': 0}, 'geometry': {'type': 'LineString', 'coordinates': ((12.33483000887518, 45.44213585306931), (12.33485161889236, 45.44208686156862))}}]}
```
Errore:
```
RuntimeWarning: divide by zero encountered in true_divide
  return (length + length/5*isBridge)/speed
```
Immagine dei canali con vel_max=0 (tramite QGis, canali selezionati sono in giallo):
<img width="639" alt="Schermata 2020-06-30 alle 02 01 58" src="https://user-images.githubusercontent.com/58313635/86067709-c9ee5080-ba75-11ea-9885-1069b9f3a912.png">

**Comment by freerafiki** [comment]
devo dire che questa issue e' veramente un capolavoro: chiara e concia, si capisce, si vede. TOP. 
Mi fa quasi piacere vederla, anche se e' un bug.

Una soluzione _quick and dirty_ sarebbe di usare `np.maximum( speed, 1)` (o anche nell'aggiunta al dizionario `np.maximum(1, np.minimum(speed, vel_max) )` pero forse perdiamo delle informazioni.

Dite che i canali con `VEL_MAX=0` hanno delle proprieta' particolari, come ad esempio essere vietate per barche a motore, o ordinanze strane? guarderei quello, perche' mi pareva di ricordare che ci fossero alcune cose particolari sugli shapefile. Se e solo un errore, aggiungiamo in minimum 1 e possiamo anche correggere sul database tutti quelli che hanno `VEL_MAX=0` sostituirli con `VEL_MAX=1`

**Comment by Lychfindel** [comment]
Il bug non è in realtà un bug! La maggior parte dei canali con velocità 0 sono o rii blu, oppure canali con divieto di transito! Ci sono alcuni canali che hanno velcità 0 e moltissime voci NULL, sono però tutti canali strani in aperta laguna.
Chiudo la issue, però bisogna ricordarsene per quando faremo la differenza tra barche a motore e barche a remi.
