### ISSUE TITLE
Problema conteggio ponti

### ISSUE THREAD

**Issue by lucatastrophe** [Lychfindel/v4w_website#59]
In questo percorso risultano 7 ponti
![Cattura1](https://user-images.githubusercontent.com/58741096/89425750-ab950800-d739-11ea-8027-32810d9e7129.PNG)
Ne ha mancati almeno 2!
![Cattura](https://user-images.githubusercontent.com/58741096/89425758-acc63500-d739-11ea-91a0-b5c2fd356a8a.PNG)
In effetti se tu gli chiedi di minimizzare il numero dei ponti, scegli una strada alternativa, in cui conteggia 9 ponti. 
La funzione peso di Networkx evidentemente ha contato giusto, mentre `go_again_through_the_street` no!

**Comment by freerafiki** [comment]
ponte del lovo manca anche nei ponti
![Screen Shot 2020-08-10 at 20 52 09](https://user-images.githubusercontent.com/10175720/89819270-6a429500-db4b-11ea-81f1-66036b92fe49.png)

**Comment by freerafiki** [comment]
ponte malvasia anche manca 
![Screen Shot 2020-08-10 at 20 53 51](https://user-images.githubusercontent.com/10175720/89819383-a249d800-db4b-11ea-9344-410cbb6c65dc.png)

**Comment by freerafiki** [comment]
nella versione v3 di nextcloud i ponti segnalati qua sono aggiunti come ponti (a parte meloni che effettivamente non ha gradini, e interrato, e va bene non esser ponte), + un altro paio che ho trovato (e non ho segnato, perche sono pigro)

**Comment by freerafiki** [comment]
creo una milestone per tutti i punti e una issue per ogni ponte, chiudo questa
