### ISSUE TITLE
Impossibile passare per il campo de la carità (accademia)

### ISSUE THREAD

**Issue by lucatastrophe** [Lychfindel/v4w_website#60]
C'è una disconnessione (da controllare su qgis) che impedisce il passaggio per di qua:
![Cattura4](https://user-images.githubusercontent.com/58741096/89435433-244d9180-d745-11ea-8bf3-4dd047a41fda.PNG)
Se metti il punto di partenza in mezzo al tratto che sembra tagliato, restituisce errore, non esiste il percorso. Direi quindi che il tratto è tagliato sia da un lato che dall'altro!

**Comment by freerafiki** [comment]
ho dato un'occhiata su QGIS, ma sembra tutto connesso sia in v1 che in v2 :(
