### ISSUE TITLE
Partire da dove si vuole in barca

### ISSUE THREAD

**Issue by lucatastrophe** [Lychfindel/v4w_website#62]
Questa issue si divide in due casi, ma dal punto di vista implementativo hanno gran parte in comune:
1) Se calcolo un percorso dalla mia posizione (in barca) e 
2) Se imposto un punto a caso sulla mappa che non sia sulla terra
Il sistema non dovrebbe calcolare la riva più vicina, ma il nodo più vicino sul grafo acqueo.
Entrambi i casi necessitano di un sistema per capire se sono a terra o in acqua. 
Un modo per gestire in modo semplice almeno i punti molto distanti dalle rive, sarebbe quello di mettere una condizione sul raggio di ricerca delle rive. Se non ci sono rive nel raggio di 200 metri, allora considera la posizione che stai cercando come "in barca".

**Comment by freerafiki** [comment]
implementato da luca
