### ISSUE TITLE
Aggiungere info percorso

### ISSUE THREAD

**Issue by lucatastrophe** [Lychfindel/v4w_website#66]
Aggiungere informazioni sul percorso come gli orari in cui è chiuso un canale o la stazza massima della barca

**Comment by freerafiki** [comment]
siamo andati avanti, ora ci sono le informazioni. Ma probabilmente serve un controllo piu accurato su come vanno aggiunte (e non vengono usate). Ma il 90% sembrerebbe fatto (vedi create_water_graph.... nella vecchia repo)

**Comment by freerafiki** [comment]
ci siamo
