### ISSUE TITLE
[TUTORIAL] Correzione archi QGIS

### ISSUE THREAD

**Issue by Lychfindel** [Lychfindel/v4w_website#70]
Questa è in realtà una piccola guida per correggere problemi di archi non collegati su QGIS.
Uno strumento che può aiutare è il plugin [Disconnected Island](https://github.com/AfriGIS-South-Africa/disconnected-islands) che aiuta a identificare i sottografi che non sono connessi.

Una volta identificato due archi che non sono collegati i passi per creare un nuovo arco tramite QGIS che li colleghi sono i seguenti:
**1.** Importa il file shp
<img width="1280" alt="Schermata 2020-08-10 alle 21 40 29" src="https://user-images.githubusercontent.com/58313635/89824506-80ecea00-db53-11ea-82c8-56d21a9934f9.png">

**2.** Seleziona la matita gialla per poter modificare il grafo
<img width="1280" alt="Schermata 2020-08-10 alle 21 40 33" src="https://user-images.githubusercontent.com/58313635/89824577-a0841280-db53-11ea-996b-98b759650523.png">

**3.** Seleziona "vertex tool"
<img width="1280" alt="Schermata 2020-08-13 alle 00 03 45" src="https://user-images.githubusercontent.com/58313635/90073094-e3cbb600-dcf8-11ea-92eb-b30b94e19094.png">

**4.** Seleziona la calamita, ovvero "enable snapping"
<img width="1280" alt="Schermata 2020-08-10 alle 21 40 46" src="https://user-images.githubusercontent.com/58313635/89824623-b5f93c80-db53-11ea-825f-737e30023e63.png">

**5.** Seleziona "enable snapping on intersection"
<img width="1280" alt="Schermata 2020-08-10 alle 21 40 50" src="https://user-images.githubusercontent.com/58313635/89824655-c14c6800-db53-11ea-9135-55ac39eba1a8.png">

**6.** Identifica i due archi non connessi e seleziona il primo nodo (il puntatore è diventato un mirino) [guarda giù per collegare due archi senza la presenza chiara di due nodi)
<img width="1280" alt="Schermata 2020-08-13 alle 00 05 43" src="https://user-images.githubusercontent.com/58313635/90073126-f80fb300-dcf8-11ea-97af-d8b5da0f35b7.png">

**7.** Seleziona il secondo nodo e clicca
<img width="1280" alt="Schermata 2020-08-13 alle 00 06 00" src="https://user-images.githubusercontent.com/58313635/90073183-0d84dd00-dcf9-11ea-8d28-ed04f7385383.png">

**9.** L'arco è stato allungato ed ora i due archi sono connessi!
<img width="1280" alt="Schermata 2020-08-13 alle 00 08 22" src="https://user-images.githubusercontent.com/58313635/90073306-41600280-dcf9-11ea-862a-c2ef7e73951f.png">

**10.** Clic destro sul livello del grafo e salva le modifiche ("save layer edits")
<img width="1280" alt="Schermata 2020-08-10 alle 21 43 57" src="https://user-images.githubusercontent.com/58313635/89824957-286a1c80-db54-11ea-9bed-1a2e431f3afe.png">

Le modifiche sono state salvate nel file shp. **Bravo!** Hai connesso due archi del grafo!

_Versione leggermente avanzata_
Se l'arco è proprio scollegato e quindi non c'è un vertice di un altro arco al quale collegarlo, devi creare il vertice nel secondo arco.

**5b**
Seleziona l'icona "split features"
<img width="1280" alt="Schermata 2020-08-13 alle 00 11 49" src="https://user-images.githubusercontent.com/58313635/90073745-0f02d500-dcfa-11ea-811e-e8077ecfa49c.png">

**5c**
Crea una linea che indicherà dove l'arco dovrà essere tagliato, per farlo devi cliccare il punto di partenza della linea e il punto di arrivo
<img width="1280" alt="Schermata 2020-08-13 alle 00 12 23" src="https://user-images.githubusercontent.com/58313635/90073881-54bf9d80-dcfa-11ea-8df4-91e551dc5251.png">

**5c**
L'arco è ora tagliato (ed è stato creato un nodo nel punto di intersezione)
<img width="1280" alt="Schermata 2020-08-13 alle 00 12 45" src="https://user-images.githubusercontent.com/58313635/90073982-85073c00-dcfa-11ea-83a4-50b3d71304e2.png">

Ora puoi collegare i due vertici selezionando di nuovo "vertex tool" e continuando il tutorial dal punto 6.

**Comment by freerafiki** [comment]
spostata nella WIKI
