### ISSUE TITLE
[terra] collegamento mancante san giacomo

### ISSUE THREAD

**Issue by freerafiki** [Lychfindel/v4w_website#73]
![Screen Shot 2020-08-13 at 23 55 57](https://user-images.githubusercontent.com/10175720/90191163-aa5e7d80-ddc0-11ea-84d9-c4729d0e81b5.png)
manca un qualche collegmaento, ora guardo in QGIS

**Comment by freerafiki** [comment]
![Screen Shot 2020-08-14 at 00 00 54](https://user-images.githubusercontent.com/10175720/90191478-3ffa0d00-ddc1-11ea-8820-da5c4f1cad1f.png)
In realta la connessione esiste, ma non viene scelta da networkx. Guardando, le distanze sembrano avere i metri corretti, non mi spiego perche non venga scelta la strada piu breve (spostando il marker verde funziona, come in figura)

**Comment by freerafiki** [comment]
![Screen Shot 2020-08-14 at 00 02 06](https://user-images.githubusercontent.com/10175720/90191566-6a4bca80-ddc1-11ea-84cb-134761811b36.png)
Questione di metri, se sposto il marker di partenza un po' piu in basso, va dall'altra parte. Forse sarebbe top aggiungere una funzione di debug che mostri il grafo sulla mappa

**Comment by Lychfindel** [comment]
I problemi sono due!
1. Manca un arco che passi di fronte alla vida (per non dover passare per il centro del campo)
<img width="1280" alt="Schermata 2020-08-14 alle 14 16 40" src="https://user-images.githubusercontent.com/58313635/90248836-b6d2ec80-de39-11ea-9454-66f748862b13.png">

2. Gli archi in corrispondenza dell'incrocio calle del tintor-campo s.giacomo non sono collegati
<img width="1280" alt="Schermata 2020-08-14 alle 14 16 33" src="https://user-images.githubusercontent.com/58313635/90248921-da963280-de39-11ea-8a10-ffb1de3affca.png">
