### ISSUE TITLE
[DISCUSSIONE] Gestione Input nella Barra di Ricerca

### ISSUE THREAD

**Issue by freerafiki** [Lychfindel/v4w_website#78]
Ho aggiunto delle cose nella barra, metto qua come discussione, per essere sicuro che siamo d'accordo. Se ci sono cose da cambiare possiamo farle tutti insieme, non volevo cambiare da solo troppe cose relative al funzionamento.

### FORM:

la zampa invia sempre un form tramite il metodo GET. il form consiste dei campi (input, textarea, ecc..) che abbiamo nell'HTML. Inizialmente noi cercavamo a mano di aggiungere la coordinata, ma ora ho cambiato e aggiunto un campo "segreto".

#### Cos'e il campo "segreto"? 
visto che il bottone e un form, ho agigunto un campo nascosto (senza prendere spazio) che contiene le coordinate. quando uno cerca premendo il bottone, il form viene inviato, e visto che il campo nascosto si chiama start_coord (e e end_coord l'altro) viene inviato esattamente come ci aspettiamo, e il python lo puo gestire. Quando il dizionario python contiene le coordinate (nella risposta) il campo viene settato da javascript, in modo che vengano ricordate. 

In questo modo nella barra di ricerca noi possiamo sempre scrivere stringhe (la mia posizione per esempio, ma non e ancora implementato) e le coordinate sono su questo campo che l'utente non vedra mai. Possiamo cambiare nella card dei risultati e se vogliamo aggiungerle, nel caso qualcuno voglia sapere le coordinate.

#### da implementare
manca ancora la mia posizione
in questo momento le possibilita scrivono a mano nella barra start_coord= e end_coord=, sarebbe da aggiornare e che scrivano nel campo nascosto per coerenza

### GESTIONE INPUT

quando l'utente scrive qualcosa (non quando ha il focus), succedono cose:
 - la x appare
 - il campo "segreto" viene resettato

#### come sappiamo quando l'utente scrive?
usiamo il metodo oninput - sembra funzionare molto bene, o almeno, esattamente come serve a noi (se una persona scrive, poi clicca sulla mappa, poi di nuovo sulla barra, non viene rilanciato) resta da testare nei casi limiti e nel telefono, per capire se fa cose strane

**Comment by Lychfindel** [comment]
Questo dovrebbe essere risolto, chiudiamo?

**Comment by freerafiki** [comment]
chiduiamo
