### ISSUE TITLE
Comportamento del navigatore 

### ISSUE THREAD

**Issue by lucatastrophe** [Lychfindel/v4w_website#80]
Quando una persona usa la app per muoversi a Venezia, selezionerà la propria posizione come punto di partenza, e cercherà il posto dove vuole andare. attualmente mettiamo correttamente la posizione di partenza, ma potremmo aggiungere che l'utente continua a vedere dov'è. Questo richiederà un nuovo campo da passare a python, a meno che non lo salviamo nella cache, perché in mezzo ricarichiamo la pagina. La "modalità navigatore", potrebbe impostare uno zoom fisso intorno alla posizione, magari dopo aver mostrato una overview del percorso.

**Comment by Lychfindel** [comment]
Questo però funziona già se uno seleziona la localizzazione, quella è sempre attiva finché non viene disattivata

**Comment by freerafiki** [comment]
modalita navigatore sara diversa, ma mi pare non ci serva questa issue
