### ISSUE TITLE
Rifinitura Prepartita Ajax

### ISSUE THREAD

**Issue by freerafiki** [Lychfindel/v4w_website#83]
- la mappa diventa incliccabile nelle possibilita, ma sembra poi che non ridiventa mai cliccabile (solo quando la pagina viene ricaricata)
- il messaggio d'errore non si chiude
- se la ricerca non trova nulla ma prima avevi gia cercato qualcosa, le finestre di risultati restano aperte ma la ricerca fallisce quindi non viene disegnato nulla
- se scelgo una possibilita dalla lista, si carica, ma non c'e la finestra del risultato
- l'icona della persona viene persa

**Comment by Lychfindel** [comment]
Non riesco a replicare

- il messaggio d'errore non si chiude
- l'icona della persona viene persa

**Comment by freerafiki** [comment]
sembrano essere risolte in effetti

**Comment by freerafiki** [comment]
risolte
