### ISSUE TITLE
Su iPad (vecchio) non funziona

### ISSUE THREAD

**Issue by Lychfindel** [Lychfindel/v4w_website#84]
Su iPad con iOS 9.0.2 (molto vecchio) si carica la mappa ma non funziona nessuna ricerca.

Penso sia un problema di os e relativa versione di safari molto vecchi.

Se è effettivamente così sarebbe da mandare un messaggio d'errore o direttamente reindirizzare a una pagina in cui diciamo che non funziona.

**Comment by Lychfindel** [comment]
Confermo che e' un problema di versione ios, una volta aggiornato l'ipad ad ios 12.4.8 funziona tutto correttamente

**Comment by freerafiki** [comment]
beh allora chiudiamo
