### ISSUE TITLE
Tiles senza usare OSM server

### ISSUE THREAD

**Issue by Lychfindel** [Lychfindel/v4w_website#89]
Sembra sia possibile in maniera semplice avere le tiles in locale senza dover fare ogni volta richiesta a OSM:
https://stackoverflow.com/questions/43608919/html-offline-map-with-local-tiles-via-leaflet

Il vantaggio sarebbe ovviamente non dover più fare affidamento sui server di OSM e, in più, poter personalizzare la mappa a nostro piacimento.

Ovviamente il problema arriva quando le tiles sono tante, però visto che noi vogliamo avere solo la laguna secondo me potrebbe essere una soluzione fattibile. Bisognerebbe anche contare i pro e i contro di avere solo venezia (o magari pensare se si riesce a fare una versione mista con venezia scaricata e tutto il resto richiesto da OSM)

Secondo me sarebbe da provare a scaricare tutte le tiles che ci servono per capire quanto spazio occupano e, nel caso non sia troppo, testare questa soluzione!

**Comment by freerafiki** [comment]
ora va grazie a tiles.dequa.it (la nuova versione)
