### ISSUE TITLE
calcolo strada usando i dati di altimetria e il livello attuale della marea

### ISSUE THREAD

**Issue by freerafiki** [Lychfindel/v4w_website#9]

**Comment by Lychfindel** [comment]
Attualmente il percorso basato su livello acqua funziona, ma ci sono un po' di dettagli da chiarire e implementare:

- cosa succede se non c'è un percorso senza acqua?
- cosa succede se si parte/arriva in un punto sotto acqua?

Riguardo al primo punto attualmente noi mettiamo semplicemente un peso molto alto se c'è acqua, quindi nel caso non ci siano percorsi all'asciutto lui farà comunque quello più breve anche se sotto acqua. Io proporrei di mettere un peso proporzionale a quanto l'arco è sotto acqua, in modo comunque da privilegiare percorsi "poco" sotto acqua, perché ovviamente avere un centimetro d'acqua non è la stessa cosa di averne 30.

Ovviamente comunque dovremmo dare avvisi che alcune parti sono sotto acqua.

**Comment by Lychfindel** [comment]
Bisogna decidere come salvare i dati dell'acqua alta e come accedervi.
Dai dati del comune noi abbiamo (tutti i nomi hanno il link collegato):

1. [Livello attuale della marea](https://dati.venezia.it/sites/default/files/dataset/opendata/livello.json): dato puntuale, aggiornato ogni 5 minuti
2. [Previsione dei prossimi tre giorni](https://dati.venezia.it/sites/default/files/dataset/opendata/previsione.json): dati in forma di max-min, aggiornato "in genere" tre volte al giorno
3. [Marea astronomica](https://dati.venezia.it/sites/default/files/dataset/opendata/as2020min.json): dati ad intervalli di 5 minuti, un unico file per tutto l'anno

La mia proposta è di creare un database con i dati della marea e di accederci ogni volta che uno fa una richiesta di percorso senza acqua alta.

Il database io lo immagino così:
- i dati ad intervalli di 5 minuti (esattamente come i dati della marea astronomica), ogni riga un nuovo dato (ci sarebbero quindi circa 100k righe, non so se questo sia un problema…)
- il database viene inizializzato con i dati della marea astronomica
- tre volte al giorno chiediamo le previsioni al comune, facciamo un fit dei massimi e minimi e aggiorniamo le righe dei tre giorni successivi sulla base delle previsioni
- se la marea prevista è più alta di 90cm aggiorniamo il db con i dati puntuali 

Questo metodo secondo me dovrebbe risparmiarci delle chiamate al sito del comune (perché alla fine che la marea sia 40 o 45 cm poco cambia), bisogna per ragionare su come aggiornare il db con i dati puntuali.
La soluzione più semplice è ovviamente fare una chiamata al sito del comune ogni 5 minuti.
Un'altra possibile soluzione semplice è fare una chiamata al sito del comune ogni volta che qualcuno fa una ricerca con acqua alta.
Un'ultima soluzione che mi viene in mente è fare una chiamata la prima volta che una persona fa una ricerca, salvare il dato nel db e per le successive chiamate utilizzare il dato del db.
