### ISSUE TITLE
Calcolare percorsi più "dritti"

### ISSUE THREAD

**Issue by freerafiki** [Lychfindel/v4w_website#90]
Un mio amico mi ha fatto notare che effettivamente l'algoritmo a volte risolve il problema in maniera ottima per un computer (tempo più breve) ma molto confuso per un umano (girando per mille callette super arzigogolato), e quindi mi domandavo se avesse senso cercare di penalizzare le svolte.

Un esempio:
![WhatsApp Image 2020-10-05 at 16 04 54](https://user-images.githubusercontent.com/10175720/95264056-08429b00-082f-11eb-8f09-398aeaf137ca.jpeg)
![WhatsApp Image 2020-10-05 at 16 05 41](https://user-images.githubusercontent.com/10175720/95264066-0aa4f500-082f-11eb-93f6-ee82922f0301.jpeg)

sebbene probabilmente sia più corto, e probabilmente più giusto, è vero che una strada dritta sarebbe più normale per un utente medio. 
Ora, la soluzione più semplice mi sembra quella di ritornare più soluzioni, ma ciò non garantisce che le altre siano dritte :/ 

Pensavo, se andiamo a modificare la funzione peso in modo da avere l'informazione sugli archi precedenti, si potrebbe calcolare l'angolo tra i due archi, l'ultimo e il corrente, e usare una funzione penalità che da un tempo 0 se l'angolo è dritto (0 gradi o 180 o dipende dal sistema di riferimento) e un tempo positivo (quindi come di attesa, o di transizione per girare) nel caso in cui l'angolo inizi a crescere. 
Poi da là ci si può anche sbizzarrire, cercare due strade parallelamente (la più corta e la più dritta, magari esagerando il tempo di penalità per le curve), o anche lasciare all'utente la personalizzazione (con uno slider?) di quanto "dritto" o "corto" lui voglia il percorso?

Forse però è macchinoso e inutile/esagerato, lo metto qua come discussione

**Comment by Lychfindel** [comment]
Credo sia solo un problema di grafo che è non collegato
![image](https://user-images.githubusercontent.com/58313635/95264768-3e344f00-0830-11eb-9a15-ce27cc1d080b.png)

**Comment by freerafiki** [comment]
hahaha mille seghe mentali per nulla - ma almeno abbiamo trovato un nuovo bug

**Comment by Lychfindel** [comment]
Issue chiusa perché non è un bug, ma contestualmente apro una issue per l'errore dell'arco
