### ISSUE TITLE
pwa su iphone - mancano dei tasti 

### ISSUE THREAD

**Issue by lucatastrophe** [Lychfindel/v4w_website#94]
il ? per esempio, ma anche la geolocalizzazione

**Comment by Lychfindel** [comment]
Puoi scrivere un po' di dettagli in piu'?
Versione ios? Funziona correttamente da browser? Sia da safari che da altri browser installati?

**Comment by Lychfindel** [comment]
Io da iphone pwa vedo tutti i tasti, @lucatastrophe riesci a descrivere meglio il problema? Altrimenti chiudo

**Comment by freerafiki** [comment]
faremo app
