### ISSUE TITLE
Passerelle

### ISSUE THREAD

**Issue by freerafiki** [Lychfindel/v4w_website#98]
Per le passerelle modifichiamo manualmente i nostri archi 

aggiungiamo 2 campi sugli archi che le hanno 
 - 1: altezza passerella (25 cm nel caso in cui ci siano solo i cavalletti da 25, o 50 nel caso in cui ci sono entrambi)
 - 2: altezza previsione marea per essere attive (quota cm / ZPS nei file del comune)

Dati da qui:
https://www.comune.venezia.it/content/percorsi-passerelle-20152016

Top:
creiamo un nostro file gis da condividere con la comunità con le passerelle

**Comment by Lychfindel** [comment]
Le passerelle sono correttamente inserite nel grafo
