### ISSUE TITLE
Routing utilizzando librerie esterne

### ISSUE THREAD

**Issue by Lychfindel** [Lychfindel/v4w_website#99]
Esistono librerie di routing esterne che sembrano funzionare bene anche a venezia selezionando i punti sulla mappa, una delle più usate è [Graphhopper](https://github.com/graphhopper/graphhopper).

**Pro**

- Graphhopper è open source
- Può essere utilizzato tramite api al loro server o anche installando il tutto in locale
- È molto veloce
- Crea il grafo direttamente con i dati delle strade di OSM (il grafo del comune ha abbastanza bug)

**Contro**
- È scritto in Java
- Non è triviale la personalizzazione che vogliamo noi (ponti, acqua alta, percorsi in barca)

Qua la repository: https://github.com/graphhopper/graphhopper
Qua la documentazione delle api: https://docs.graphhopper.com
Qua un esempio di mappa: https://graphhopper.com/maps/
Qua un esempio delle api: https://graphhopper.com/api/1/examples/ (per il percorso a venezia non funziona perché qua calcola i percorsi in macchina)

**Comment by Lychfindel** [comment]
Ho una buona e una cattiva notizia.
La buona è che pur con i nostri bug siamo meglio di OSM.
La cattiva è che non possiamo usare le librerie che prendono i dati da OSM perché i dati di OSM hanno molti errori.
<img width="1280" alt="Schermata 2020-11-16 alle 16 07 22" src="https://user-images.githubusercontent.com/58313635/99269005-233cfd80-2826-11eb-8351-ac86eb7ffa0e.png">
Qua ad esempio un sacco di archi mancanti (succede molto spesso su campi e strade molto larghe come via garibaldi)

**Comment by freerafiki** [comment]
usiamo graphtool
